In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv('spam.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
Label        5572 non-null object
EmailText    5572 non-null object
dtypes: object(2)
memory usage: 87.2+ KB


In [16]:
df['Label'] = df.Label.map({'ham':0, 'spam':1})

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['EmailText'], 
                                                    df['Label'], 
                                                    test_size =0.2, 
                                                    random_state=1)


print('Number of rows in the total set: {}'.format(df.shape[0]))
print('Number of rows in the training set: {}'.format(X_train.shape[0]))
print('Number of rows in the test set: {}'.format(X_test.shape[0]))

Number of rows in the total set: 5572
Number of rows in the training set: 4457
Number of rows in the test set: 1115


In [8]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()

In [9]:
training_data = count_vector.fit_transform(X_train).toarray()
testing_data = count_vector.transform(X_test).toarray()

In [10]:
frequency_matrix = pd.DataFrame(training_data,columns = count_vector.get_feature_names())
frequency_matrix.head()

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0   0    0       0             0     0     0            0            0   
1   0    0       0             0     0     0            0            0   
2   0    0       0             0     0     0            0            0   
3   0    0       0             0     0     0            0            0   
4   0    0       0             0     0     0            0            0   

   0125698789  02  ...  zeros  zindgi  zoe  zogtorius  zoom  zouk  zyada  ¹ã  \
0           0   0  ...      0       0    0          0     0     0      0   0   
1           0   0  ...      0       0    0          0     0     0      0   0   
2           0   0  ...      0       0    0          0     0     0      0   0   
3           0   0  ...      0       0    0          0     0     0      0   0   
4           0   0  ...      0       0    0          0     0     0      0   0   

   âªve  å½ã  
0     0    0  
1     0    0  
2     0    0  
3     0    0  
4     0    0  

[5 rows x 7779 columns]

In [11]:
testing_data


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
clf = LogisticRegression(random_state=0).fit(training_data, y_train)

C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [13]:
predictions = clf.predict(testing_data)

In [14]:
predictions


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
print('Accuracy score: ', format(accuracy_score(y_test, predictions)))
print('Precision score: ', format(precision_score(y_test, predictions)))
print('Recall score: ', format(recall_score(y_test, predictions)))
print('F1 score: ', format(f1_score(y_test, predictions)))
print('\nConfusion Matrix :\n', confusion_matrix(y_test, predictions))

Accuracy score:  0.9910313901345291
Precision score:  0.9849624060150376
Recall score:  0.9424460431654677
F1 score:  0.9632352941176471

Confusion Matrix :
 [[974   2]
 [  8 131]]
